import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { withTheme } from "@/theme/withTheme";
import themeRegistery from "@/theme/themeRegistery";
const inter = Inter({ subsets: ["latin"] });

export interface Product {
  brand: string;
  category: string;
  description: string;
  id: number;
  price: number;
  stock: number;
  thumbnail: string;
  title: string;
}

export default function Home({
  products,
  theme,
}: {
  products: Array<Product>;
  theme: string;
}) {
  const Catalog = themeRegistery.getComponent(`Catalog`, theme);
  const Header = themeRegistery.getComponent(`Header`, theme);
  return (
    <>
      <Head>
        <title> Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className} theme--${theme}`}>
        <div className="main">
          <div className="content">
            <Header></Header>

            {theme === "xyz" && (
              <section className="banner">
                <Image
                  src={`https://picsum.photos/seed/picsum/900/1600`}
                  width={1600}
                  height={500}
                  alt={""}
                />
              </section>
            )}

            <Catalog products={products} />

            {/* {theme === 'xyz' ? <section className='table'>
            <table style={{width: '100%'}}>
              <thead>
              <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
              </tr>
              </thead>
              <tbody>
              {products.map(product =>  (
                
                <tr key={product.id}>
                    <td>{product.title}</td>
                    <td>{product.category}</td>
                    <td>${product.price}</td>
                </tr>
              
            ))}
              </tbody>
            </table>
          </section> : 
          <section className='catalog'>
          {products.map(product => 
            <article className='product' key={product.id}>
               <h3> {product.title}</h3>
               <Image className='img' src={product.thumbnail} alt={product.title} width={600} height={400} />
               <p className="description">
                  {product.description}
               </p>
            </article>
          )}
          </section>
          } */}
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = withTheme(async (context: any) => {
  const resp = await fetch(`https://dummyjson.com/products`);

  const json = await resp.json();
  return {
    props: {
      products: json.products,
    },
  };
});
